export const DELETE_USER = 'DELETE_USER';
export const ADD_RATING_USER_ROW = 'ADD_RATING_USER_ROW';
export const SAVING_ERROR = 'SAVING_ERROR';
export const RESET_SAVING_ERROR = 'RESET_SAVING_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_ENTITIES = 'ADD_ENTITIES';


